baseurl = "http://example.org/"
languageCode = "en-us"
title = "Hugo Cards"
theme = "hugo-cards"
themesDir = "../.."
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""
  
  custom_css = ["css/custom.css"]

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"

